### ISSUE TITLE
config file failure

### ISSUE THREAD

**Issue by DarkmoonRabbit** [azerothcore/mod-transmog#1]
E.g:
Transmogrification.AllowMixedArmorTypes = 1
Transmogrification.AllowMixedWeaponTypes = 1
Transmogrification.AllowFishingPoles = 1

**Comment by sucofog** [comment]
???

**Comment by sucofog** [comment]
Config not working @DarkmoonRabbit

**Comment by Yehonal** [comment]
Config work as intended, otherwise please post your errors

Closed
