### ISSUE TITLE
The problem of not displaying models after illusion

### ISSUE THREAD

**Issue by yukijean** [azerothcore/mod-transmog#108]
First of all, thank you for providing templates and tutorials. I have passed the tutorial and installed the Phantom template. The corresponding NPC has also been added to the game. But when I finish the Phantom, the model of the equipment will not be displayed in the character panel. You can see the following pictures. The equipment bar will not be displayed, and the character model will not be displayed. Please ask me what caused this problem. Thank you very much!
![123](https://user-images.githubusercontent.com/124695463/217270560-a56b73b3-06b4-427b-8714-5f82a78c9ddf.jpg)
![321](https://user-images.githubusercontent.com/124695463/217270619-45abb853-91fb-40d1-bbb6-afb8993d48b0.jpg)

**Comment by Ceikry** [comment]
I recommend closing this issue, seems it has already been fixed.

**Comment by Helias** [comment]
> I recommend closing this issue, seems it has already been fixed.

Thanks!
