### ISSUE TITLE
Personal suggestions for this module

### ISSUE THREAD

**Issue by zxnhrdz** [azerothcore/mod-transmog#109]
The function of this module is comprehensive, but it's a pity that some appearances can't break through the restrictions of professional use.
Example: For example, the deputy of the legal profession turns into a shield.
For example, the wand of the legal profession turns into a bow.
Similarly, melee classes do not support the illusion of deputies and wands.
To this problem, it may be a big project. Just a little advice!

**Comment by Ceikry** [comment]
I recommend closing this issue as it's nondescriptive and written in broken English
