### ISSUE TITLE
Suggestions on Legion-style appearance collection system.

### ISSUE THREAD

**Issue by zxnhrdz** [azerothcore/mod-transmog#111]
If the profile is enabled
Transmogrification.UseCollectionSystem=1

Because there are too many items collected, it is necessary to use the fitting room to browse the effects of the items and equipment. But at present, the system has no try-on function, and I hope to improve it. thank you！

![image](https://user-images.githubusercontent.com/110412571/219594709-d8e7599a-26b3-435c-a5c8-2bd9cae0df87.png)

**Comment by Nyeriah** [comment]
This can't be achieved with the current gossip implementation, because you can't click links in gossip chat bubbles.

**Comment by ZhengPeiRu21** [comment]
There may be a possibility to use a vendor UI to display the items, which would allow for previewing, but this would requiring re-writing much of the module, so no one has work on it yet: https://github.com/azerothcore/mod-transmog/issues/43

In the meantime, this addon will allow you to see your collection and preview all appearances, though it is separate from the transmog vendor UI: https://github.com/ZhengPeiRu21/transmog-addons

**Comment by zxnhrdz** [comment]
> There may be a possibility to use a vendor UI to display the items, which would allow for previewing, but this would requiring re-writing much of the module, so no one has work on it yet: #43
> 
> In the meantime, this addon will allow you to see your collection and preview all appearances, though it is separate from the transmog vendor UI: https://github.com/ZhengPeiRu21/transmog-addons

Your reply is very helpful to me, thank you!
