### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by assada** [azerothcore/mod-transmog#112]
log: https://gist.github.com/assada/068435b470644a1b9a98d94b61a056d3
video: https://youtu.be/uwEwc98Dggc
AC: https://github.com/azerothcore/azerothcore-wotlk/commit/edb9df9347a14454341bbf2be6fd13be8d9fe4b4
Transmog: https://github.com/azerothcore/mod-transmog/commit/21d63e8d723e76bdb495a35e50e742593cb1b964

**Comment by assada** [comment]
From discord discussion:
```
M'Dic#0865: ...it seems like its missing a null check...
Foe#5438: target should be checked whether it's nil or not https://github.com/azerothcore/mod-transmog/blob/master/src/transmog_scripts.cpp#L39
```

**Comment by svenbledt** [comment]
#135 same here

**Comment by Helias** [comment]
I made a possible fix, please test
