### ISSUE TITLE
Update/port script from Rochet2's latest transmog

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-transmog#12]
Rochet2 told me the script used in this module is based on the transmog version from 2014-2015. It has received many updates since then.
https://rochet2.github.io/Transmogrification.html

That would be worth a go.

A quote from Rochet2 regarding the port:

>Its always possible to add hooks to the core everywhere. But the hooks are not that well generally applicable .. also some of the core modifications required are very weird to have as hooks.. maybe some of the things that require wierd hooks could be recoded to require less weird hooks .. but I dont know

And a changelog of what we're missing (we are approximatively on version 4 and transmog is at v6):

```
6.0

    Removed mutex locks - Different code style, works with ACE and boost, probably more efficient
    Added regex checking for preset name
    Fixed random properties not registering as item stats (Thanks Aokromes)
    Made the code / patch compatible with herbs+veins patch (Thanks Aokromes)
    Moved to bithub - Allows autogenerate patch and diff and management is easier:
    https://github.com/Rochet2/TrinityCore/tree/transmog
    Gist was at: https://gist.github.com/Rochet2/2c8765b53f8dda1e296a

5.6

    Fixed few linux compile warnings
    Moved to GIST
    Old versions etc still available from: https://drive.google.com/folderview?id=0Bx5knS2IsjatTlVtWHRwbUN3VlE&usp=sharing

5.5

    Updated to latest TC rev
    Fixed some tabs to spaces
    Fixed a warning on gcc

5.4

    Updated to latest TC rev

5.3

    Rewrote transmogrification logic to be blizzlike.
    Implemented multithread support.
    Tweaked saving to work so that your data is saved whenever the player is saved.
    This means that crashes can not be abused and DB wont have SQL executing and querying all the time.

5.2

    Some logic fixes and other

5.1

    Config options should now work properly. Please notify here if some still bug
    Can transmog bows with guns and crossbows
    Can transmog cloth to leather with config settings set
    Can transmog robes with chest pieces
    You should now be able to view the info menus with the new NPC
    Allow shirt's to be transmogrified (were shown in menu but you weren't able to before)
    Mirror image (mage spell) should now correctly copy the transmogrified outfit. Before it still got your old item displays.
    Added new config options:

5.0

    Ripped cata branch functions and thus altered how everything is coded pretty much.
    Dropped translation support
    Added colored item links as well as icons all over the place
    Added new feature: Sets
    Added many config options, for example to allow cloth and plate to be transmogrified with each other
```

**Comment by yuanf225** [comment]
Doesn't anyone care about this message?

**Comment by Yehonal** [comment]
Maybe @Rochet2 could work with me on it. I'll create hooks for those updates and eventually change the core to host what can't be done via hooks (I think tiny stuff tbh) I'd glad to work on it but:
1) we need to keep it as a module.
2) it's better that the original author could maintain it.

The idea behind hooks and core changes is: whatever something can be a conf (worldserver or cmake) that keeps the logic of a game server framework then it's good to change the core supporting it.
What we MUST not do instead is messing the core with transmog-specific hacks. The job is pretty easy and I can definetly give an hand on help you guys deciding what can do in core and what must do in module.

But again, not alone. Feel free to organize the job on discord with me

**Comment by Helias** [comment]
reference of the display vendor https://github.com/Rochet2/TrinityCore/tree/transmogvendor_3.3.5/src/server/scripts/Custom/TransmogDisplayVendor

duplicate issue https://github.com/azerothcore/mod-transmog/issues/36
