### ISSUE TITLE
Issue with custom Races

### ISSUE THREAD

**Issue by svenbledt** [azerothcore/mod-transmog#135]
When i reach level 70 with custom races i got a crash because of mod-transmog.

[gdb.txt](https://github.com/azerothcore/mod-transmog/files/12823018/gdb.txt)

Its because of PlayerSettings that cant get after the second login. then the server crashes. i dont know how the GetSettings system works but i report at least the issue here that someone can take a look at it maybe.

**Comment by Helias** [comment]
@heyitsbench, may you can help here
