### ISSUE TITLE
Bug: "Collect appearance by pressing F4" is not working

### ISSUE THREAD

**Issue by Aldori15** [azerothcore/mod-transmog#143]
Under the Keybinds menu is an option called "Collect Appearance From Item Under Cursor".  I set this keybind to F4.

Whenever I hover over an uncollected appearance in my bags, at the bottom of the tooltip it says to press F4 to collect appearance, which is what the keybind menu is looking for.  However, hovering the mouse over the item and pressing F4 gives a "Are you sure you want to collect appearance from this item?", but clicking Yes just closes the dialog and doesn't do anything.

I was trying to use this as a workaround for the Feature Request I put here: #142 
but I thought maybe it just wasn't working because I'm a Cloth character trying to learn a Mail appearance.  But the same results even when hovering over a Cloth item and pressing F4.

![image](https://github.com/azerothcore/mod-transmog/assets/15916673/7effe232-722d-4823-81dc-fefe6b693698)

![image](https://github.com/azerothcore/mod-transmog/assets/15916673/f8974736-dfa4-4ea0-bf08-3de6cef36b4f)

**Comment by Nyeriah** [comment]
What kind of client/addon are you running? This isn't a default feature

**Comment by Aldori15** [comment]
Sorry, this is a bug with ezCollections client addon and not this repo.
