### ISSUE TITLE
Database update error

### ISSUE THREAD

**Issue by zxnhrdz** [azerothcore/mod-transmog#154]
![image](https://github.com/azerothcore/mod-transmog/assets/110412571/73612cf4-e14a-429a-8fa7-f713511600a5)

![image](https://github.com/azerothcore/mod-transmog/assets/110412571/a6833040-b707-4e83-a010-25222b1263c2)

The table "create_template_model" does not exist in the database.

**Comment by Helias** [comment]
You have to update your database, now creature_template_model exists, it's a new table since 3 days ago https://github.com/azerothcore/azerothcore-wotlk/pull/19068
