### ISSUE TITLE
`.transmog sync` does not seem to work.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/mod-transmog#167]
Likely caused by all the fmt changes, seems to have broken around the same time. Using [an addon](https://github.com/ZhengPeiRu21/transmog-addons) to keep track of learned transmogrifications and using the `.transmog sync` command in-game does not yield any changes in learned appearances. No idea if this is an issue with the module itself or the addon, but there's a problem somewhere.

**Comment by heyitsbench** [comment]
[Command results without the addon enabled](https://github.com/user-attachments/assets/a904fa2b-288c-4ce0-a57b-dca244789bae), definitely seems to be a module issue.

CC: @Kitzunu if it's something you'd like to tackle again. 😛

**Comment by Kitzunu** [comment]
No idea where it is sent. But change %u to {}

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/mod-transmog/commit/af0988099fb932f5978b8d22054641de9e8328b8
