### ISSUE TITLE
Module configuration in worldserver.conf

### ISSUE THREAD

**Issue by AldebaraanMKII** [azerothcore/mod-transmog#181]
`> Config: Missing property Transmogrification.EnableSortByQualityAndName in config file configs/worldserver.conf, add "Transmogrification.EnableSortByQualityAndName = 1" to this file or define 'AC_TRANSMOGRIFICATION_ENABLE_SORT_BY_QUALITY_AND_NAME' as an environment variable.`

why is this module`s configuration in the worldserver.conf? This is extremely bad practice.

**Comment by Nyeriah** [comment]
It’s not. It’s just the logger displaying wrong information. You can check the config file yourself.
