### ISSUE TITLE
the server shuts down when transfiguring

### ISSUE THREAD

**Issue by nerows** [azerothcore/mod-transmog#25]
when transfiguring legendary objects the server shuts down

**Comment by Stoabrogga** [comment]
I'll take a look at this.

**Comment by Stoabrogga** [comment]
Sorry, but I cannot reproduce the error, tested with "Shadowmourne" and "Sulfuras, Hand of Ragnaros", both using them as source and destination for transmog.

**Comment by BarbzYHOOL** [comment]
maybe related to some config options

can you post your transmog module config @nerows ?

**Comment by milestorme** [comment]
cannot reproduce

**Comment by Winfidonarleyan** [comment]
Where's one proof?
