### ISSUE TITLE
Display if an item has been transmogrified

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-transmog#30]
If we could see when an item has been transmogrified, it would be quite nice. I don't know it can be done without client edits though

Also a way to know which item is transmogrified into what, maybe with a command?

**Comment by BarbzYHOOL** [comment]
Also if it could display the new state of "soulbound", it'd be cool

**Comment by eTzmNcbkrng** [comment]
https://github.com/Wrath-AddOns/transmog-addons
