### ISSUE TITLE
Config options not implemented??

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-transmog#33]
What do these things do? it seems like it does nothing

```
Logger.custom.transmog
Transmogrification.EnableTransmogInfo
```

**Comment by Stoabrogga** [comment]
"Logger.custom.transmog" can be removed from the comments in the config file. "Transmogrification.EnableTransmogInfo" is used here:
https://github.com/azerothcore/mod-transmog/blob/3faf38ae6cee04e8f2051ecef6d4000ca7e8d677/src/transmog_scripts.cpp#L35-L36
