### ISSUE TITLE
Transmog display - azerothcore

### ISSUE THREAD

**Issue by V3nomAnc3r** [azerothcore/mod-transmog#36]
Hey can some one update transmog display for azerothcore

https://github.com/Rochet2/TrinityCore/tree/transmogvendor_3.3.5/src/server/scripts/Custom/TransmogDisplayVendor

**Comment by yuanf225** [comment]
Yeah, it's another way of showing it, it's cool, but nobody seems to want to update it

**Comment by Helias** [comment]
duplicate of https://github.com/azerothcore/mod-transmog/issues/12
