### ISSUE TITLE
Worldserver don't work

### ISSUE THREAD

**Issue by wowissues** [azerothcore/mod-transmog#37]
Hi guys, i'm use the latest version of azerothcore, and i'm getting this error when i'm starting worldserver:

`SQL: DELETE FROM custom_transmogrification WHERE NOT EXISTS (SELECT 1 FROM item_instance WHERE item_instance.guid = custom_transmogrification.GUID)
ERROR: [1146] Table 'acore_characters.custom_transmogrification' doesn't exist
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.`

What i need to do? Execute this query or what?

**Comment by wowissues** [comment]
i fix this, idk why but transmorg.sql don't execute into my db

**Comment by Hibar84** [comment]
Hello @wowissues , I have the same issue, how did you fix it ?

**Comment by Helias** [comment]
> Hello @wowissues , I have the same issue, how did you fix it ?

he executed the SQL file included in the repository
