### ISSUE TITLE
 Error when compiling

### ISSUE THREAD

**Issue by Madera95** [azerothcore/mod-transmog#51]
Today I tried several times to compile the core with the said modules. However, the same error always appears to me with a large number of modules. Should I also enter this with the others or is this a general problem?

I used the newest REV vom AC

`[100%] Linking CXX executable worldserver
/usr/bin/ld: ../scripts/libscripts.a(ScriptLoader.cpp.o): in function `AddScripts()':
/home/worldt/azerothcore/build/src/server/scripts/gen_scriptloader/static/ScriptLoader.cpp:77: undefined reference to `Addmod_ah_bot_masterScripts()'
/usr/bin/ld: /home/worldt/azerothcore/build/src/server/scripts/gen_scriptloader/static/ScriptLoader.cpp:78: undefined reference to `Addmod_cfbg_masterScripts()'
/usr/bin/ld: /home/worldt/azerothcore/build/src/server/scripts/gen_scriptloader/static/ScriptLoader.cpp:79: undefined reference to `Addmod_transmog_masterScripts()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/build.make:191: src/server/worldserver/worldserver] Error 1
make[1]: *** [CMakeFiles/Makefile2:1099: src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
`

**Comment by Winfidonarleyan** [comment]
Clean make cache and regenerate project

**Comment by Madera95** [comment]
Regardless of whether I emptied the cache or edited simple things in the ScriptLoader.cpp, it expresses this error to me. There seems to be something wrong with the API.

**Comment by Winfidonarleyan** [comment]
Show full cmake log

**Comment by Madera95** [comment]
I found the mistake. I had to edit the loader. I had to change the following so that the compile ran properly.

In "transmog_loader.cpp at Line 10.

Edit to: void Addmod_transmog_masterScripts()

**Comment by Winfidonarleyan** [comment]
Aha, please use `git clone` next time
