### ISSUE TITLE
Problems with Transmog Module

### ISSUE THREAD

**Issue by strom1990** [azerothcore/mod-transmog#53]
Hey, so i installed the module following the instructions. I can add the npc but when i talk to him, i onlyy get Greetings and no options for transmog.

**Comment by zqgmzq** [comment]
@Helias @UltraNix @Winfidonarleyan
i think its easy to fix but i dont know where to search
can u help with this problem

**Comment by UltraNix** [comment]
Have you updated your databases with sql files from https://github.com/azerothcore/mod-transmog/tree/master/data/sql?

**Comment by zqgmzq** [comment]
yep, npc and all text in db but module not working

**Comment by strom1990** [comment]
![Uploading D8EACCE5-AF53-43CB-8C59-2984BEB6DD15.jpeg…]()

**Comment by pe93** [comment]
i get a Warning when i import the sql for the characters database:
Something like "Warning: Integer display width is deprecated and will be removed in a future release. 
Warning: INteger display width is deprecated and will be removed in a future release.
Warning: "utf8" is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future relase. Please consider using UTF8MB4 in order to be unambiguous.

**Comment by zqgmzq** [comment]
sory, its ok, but now npc start work only after server reboot

**Comment by pe93** [comment]
when i rebuild containers i get the following:
[ 43%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-transmog-master/src/Transmogrification.cpp.o
/azerothcore/modules/mod-transmog-master/src/Transmogrification.cpp:206:41: fatal error: no member named 'nameSuffix' in 'ItemRandomSuffixEntry'
                suffix = itemRandEntry->nameSuffix;
                         ~~~~~~~~~~~~~  ^
1 error generated.
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/build.make:8404: src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-transmog-master/src/Transmogrification.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1120: src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

real    0m14.091s
user    0m2.861s
sys     0m1.585s
Fixing EOL...

**Comment by zqgmzq** [comment]
tested on https://github.com/azerothcore/azerothcore-wotlk/commit/d35c6b602234dfc313066a2de9db74eb97798c75
build is ok

**Comment by Winfidonarleyan** [comment]
![image](https://user-images.githubusercontent.com/18329778/140047944-9ac377e6-de82-4444-8547-bd1b7cbf9b75.png)
