### ISSUE TITLE
Compile fail

### ISSUE THREAD

**Issue by Dude100** [azerothcore/mod-transmog#54]
Linux 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
Core commit:05c473443e4d3b9ab905de0c20c365976b87696b

https://pastebin.com/FXGQJeHB

**Comment by Winfidonarleyan** [comment]
![image](https://user-images.githubusercontent.com/18329778/140047920-8a0a17f8-a4a2-4ae3-87ad-dabc491ec7d2.png)
