### ISSUE TITLE
[IDEA] We want a way to disable transmog per-player

### ISSUE THREAD

**Issue by Yehonal** [azerothcore/mod-transmog#60]
In a nutshell:

There should be an in-game command and a gossip option at the transmog NPC to allow people to disable the transmog.

Disabling transmog means that:

1. Your equip will be shown to you and to the others with the original displayId
2. The equip of the other players will be shown with the original displayId.

**Comment by Nyeriah** [comment]
One thing I wanted to address before moving on with this is to have a way to store character specific settings in the core, something that could be used to extend certain core features (like allow players to skip receiving broadcast/battleground queue anouncers) and that all other custom modules (like this one) could also use.

It would pave the way to enabling features like disabling the pvp queue announcers if players don't wish to see it, but also implement other features that were requested, such as choosing which race you're assigned when you join a cfbg.

I want to come up with something so we can get started on it but I'm not sure about the best design yet, but I'll still come up with something anyway so we can discuss it.

**Comment by Yehonal** [comment]
> One thing I wanted to address before moving on with this is to have a way to store character specific settings in the core, something that could be used to extend certain core features (like allow players to skip receiving broadcast/battleground queue anouncers) and that all other custom modules (like this one) could also use.
> 
> It would pave the way to enabling features like disabling the pvp queue announcers if players don't wish to see it, but also implement other features that were requested, such as choosing which race you're assigned when you join a cfbg.
> 
> I want to come up with something so we can get started on it but I'm not sure about the best design yet, but I'll still come up with something anyway so we can discuss it.

Interesting. We can discuss it privately and see what's the best design for it

**Comment by Nyeriah** [comment]
Done after:
- https://github.com/azerothcore/azerothcore-wotlk/pull/9961
- https://github.com/azerothcore/mod-transmog/pull/62/files
