### ISSUE TITLE
Compile faild

### ISSUE THREAD

**Issue by xclid** [azerothcore/mod-transmog#68]
https://github.com/azerothcore/azerothcore-wotlk/commit/0b02ba87fc60d538b78a401604eb8955b895515f

https://github.com/azerothcore/mod-transmog/commit/b4439fcddf2fd4f0fcf5d9fbf9718a5404c3bfd3

`/root/azerothcore/modules/mod-transmog/src/Transmogrification.cpp:53:43: fatal error: no member named 'GetUInt8' in 'Field'
            uint8 PresetID = (*result)[0].GetUInt8();
                             ~~~~~~~~~~~~ ^
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:1343: modules/CMakeFiles/modules.dir/mod-transmog/src/Transmogrification.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/root/azerothcore/modules/mod-transmog/src/transmog_scripts.cpp:413:87: fatal error: no member named 'GetUInt32' in 'Field'
                ObjectGuid itemGUID = ObjectGuid::Create<HighGuid::Item>((*result)[0].GetUInt32());
`

**Comment by acidmanifesto** [comment]
resolved now
