### ISSUE TITLE
Module not added to build

### ISSUE THREAD

**Issue by VeenixO** [azerothcore/mod-transmog#70]
I am able to add the module to the Azerothcore source modules folder, then make it with cmake (shows tmog module listed), then after making a new build with visual studio and adding the sql I am able to spawn the npc but it only greets me. I don't see any tmog options.
My guess is that the script isn't created with cmake, I checked the modules folder under the build folder and I see all modules in there except for the tmog module.

Any idea how to fix this?

I did everything the installation guide said yet it seems to somehow not add the module to the actual build.

**Comment by Winfidonarleyan** [comment]
need use git clone

**Comment by VeenixO** [comment]
Did that, same issue.

**Comment by Winfidonarleyan** [comment]
> Did that, same issue.

Okay.

1. Show the folder `./modules`
2. Show core logs 
3. Show file `./build/modules/gen_scriptloader/static/ModulesLoader.cpp`

**Comment by VeenixO** [comment]
>     2. Show core logs

Do you mean the server.log and auth.log or is there a different log file u need?

**Comment by Winfidonarleyan** [comment]
> > ```
> > 2. Show core logs
> > ```
> 
> Do you mean the server.log and auth.log or is there a different log file u need?


`Appender.Server`

**Comment by VeenixO** [comment]
> 

Can't seem to find any Appender.Server file. Anyways here is what I did find.
(Though I could upload the .cpp file itself, seemingly I can't so opened it in notepad to quickly make a screenshot)

![BuildModules](https://user-images.githubusercontent.com/24385831/153239725-7402eabb-45a4-46d0-b3ee-097f7d5e34ab.png)
![SourceModules](https://user-images.githubusercontent.com/24385831/153239734-070ecbc3-3c3a-4b16-82a6-569fbd8228d2.png)
![ModulesLoader](https://user-images.githubusercontent.com/24385831/153239968-07b1a7ec-e280-47d2-9e71-199f70d2d799.png)

**Comment by Winfidonarleyan** [comment]
`Appender.Server` no file, this config option for location server file log. Okay, so, you applied sql files from this?

https://github.com/azerothcore/mod-transmog/tree/master/data/sql

**Comment by Tony931023** [comment]
in the .config Transmogrification.EnableTransmogInfo = 0 for enable options

**Comment by WowChenEd** [comment]
> yep, added all of those. The npc itself exists and can be spawned but does only greet.

do you fix it?  same problem with you

**Comment by Helias** [comment]
it should be fixed now
