### ISSUE TITLE
No transmog menu

### ISSUE THREAD

**Issue by WowChenEd** [azerothcore/mod-transmog#89]
![image](https://user-images.githubusercontent.com/17425810/178137239-6b95e00d-4134-4fee-bceb-ca8512f3f42a.png)

**Comment by WowChenEd** [comment]
![image](https://user-images.githubusercontent.com/17425810/178139531-9a58f337-02ac-4bdc-88d7-cda16a950b79.png)

![image](https://user-images.githubusercontent.com/17425810/178139540-680bde6b-a041-4496-90f7-1e76fdd07b8f.png)

**Comment by acidmanifesto** [comment]
U need to rerun cmake after you put the module in the module folder then rebuild.

**Comment by WowChenEd** [comment]
> U need to rerun cmake after you put the module in the module folder then rebuild. You also need to run the sql files.

suo.nz/1nOt2F 
yes i have rebuild it but another exception occured and even cannot login

**Comment by WowChenEd** [comment]
![Uploading 1657466640053.jpg…]()

**Comment by acidmanifesto** [comment]
> ![Uploading 1657466640053.jpg…]()
> 

![Screenshot_20220710-114703_Free Adblocker Browser.jpg](https://user-images.githubusercontent.com/16887899/178151975-c06e3c22-8708-4e97-a1aa-1bcfd9fdc1e5.jpg)

**Comment by WowChenEd** [comment]
sorry for the broken image.
![image](https://user-images.githubusercontent.com/17425810/178152686-dcea0aa6-6114-4f1c-9f5b-9d8ab4ffbf57.png)

**Comment by horstt** [comment]
I am having this very same issue. 
I downloaded the module from GIT:
```
cd /home/azcore/azerothcore/modules
git clone https://github.com/azerothcore/mod-transmog.git

```
Then I wan the sql commands:
```
mysql -u acore -p'acore' -D acore_characters < /home/azcore/azerothcore/modules/mod-transmog/data/sql/db-characters/trasmorg.sql
mysql -u acore -p'acore' -D acore_world < /home/azcore/azerothcore/modules/mod-transmog/data/sql/db-world/trasm_world_NPC.sql
mysql -u acore -p'acore' -D acore_world < /home/azcore/azerothcore/modules/mod-transmog/data/sql/db-world/trasm_world_texts.sql
```
and ran the same cmake command I used when installing AzerothCore the first time. Still getting the errors that WowChenEd pasted here... 

It's my first attempt to install a module, so I might simply misunderstand the procedure required to install modules...

**Comment by horstt** [comment]
> It's my first attempt to install a module, so I might simply misunderstand the procedure required to install modules...

Okay so yeah, this was the issue :-) Steps I missed:
1. There's an 'include.sh' file in the root of the module, run it
2. Probably obvious to everyone here, but don't just run cmake, also do a build. 
After that this mod works for me!
