### ISSUE TITLE
Crashing Core

### ISSUE THREAD

**Issue by MaDmaX1337** [azerothcore/mod-transmog#96]
![image](https://user-images.githubusercontent.com/11060723/185786231-d39fb269-6298-443b-a780-6f71e0193204.png)

AzerothCore rev. 560a74e757da+ 2022-08-18 16:14:39 -0300 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Comment by Tony931023** [comment]
crash log

**Comment by MaDmaX1337** [comment]
Crash Logs
[crash log.zip](https://github.com/azerothcore/mod-transmog/files/9389413/crash.log.zip)

**Comment by Fallnight44** [comment]
I confirm, I also crash exactly the same as MaDmaX1337, here's my crash log

[crash log.zip](https://github.com/azerothcore/mod-transmog/files/9404069/crash.log.zip)

Thank you for your time and consideration 🙏

**Comment by ZhengPeiRu21** [comment]
Thank you for the reporting and the crash log. It was very helpful to find the problem. I have created a PR that will fix the issue!
